import { stepRegistry } from './stepRegistry.js';
import { getUserToken } from './gmailIntegration.js';

// ---------------------------------------------------------
// 1. SLACK INTEGRATION (`slack_send_message`)
// ---------------------------------------------------------
stepRegistry.register('slack_send_message', async (config, context) => {
  const webhookUrl = config.webhookUrl;
  const channel = config.channel || '#general';
  const text = config.text || config.message || 'Notification from AutoFlow-AI';
  const token = config.token;

  if (webhookUrl) {
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, channel }),
    });

    if (!res.ok) {
      const errText = await res.text();
      throw new Error(`Slack Webhook error (${res.status}): ${errText}`);
    }

    return { sent: true, mode: 'webhook', channel, text };
  } else if (token) {
    const res = await fetch('https://slack.com/api/chat.postMessage', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ channel, text }),
    });

    const data = await res.json();
    if (!data.ok) {
      throw new Error(`Slack API error: ${data.error || 'Failed to send message'}`);
    }

    return { sent: true, mode: 'api', channel, ts: data.ts };
  } else {
    throw new Error('slack_send_message step requires either "webhookUrl" or "token" in step config.');
  }
});

// ---------------------------------------------------------
// 2. GITHUB INTEGRATION (`github_create_issue`)
// ---------------------------------------------------------
stepRegistry.register('github_create_issue', async (config, context) => {
  const owner = config.owner;
  const repo = config.repo;
  const title = config.title;
  const body = config.body || 'Automated issue created by AutoFlow-AI workflow';
  const labels = config.labels || ['autoflow-ai'];
  const token = config.token || process.env.GITHUB_TOKEN;

  if (!owner || !repo || !title) {
    throw new Error('github_create_issue step requires "owner", "repo", and "title" in step config.');
  }

  if (!token) {
    throw new Error('github_create_issue requires a GitHub Personal Access Token or GITHUB_TOKEN.');
  }

  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      'User-Agent': 'AutoFlow-AI-Workflow-Engine',
    },
    body: JSON.stringify({ title, body, labels }),
  });

  const responseData = await res.json();

  if (!res.ok) {
    throw new Error(`GitHub API Error (${res.status}): ${responseData.message || JSON.stringify(responseData)}`);
  }

  return {
    created: true,
    issueNumber: responseData.number,
    issueUrl: responseData.html_url,
    title,
    owner,
    repo,
  };
});

// ---------------------------------------------------------
// 3. GOOGLE DRIVE INTEGRATION (`google_drive_upload`)
// ---------------------------------------------------------
stepRegistry.register('google_drive_upload', async (config, context) => {
  const userId = config.userId || 'default-user';
  const fileName = config.fileName || `autoflow-doc-${Date.now()}.txt`;
  const fileContent = config.fileContent || 'Generated by AutoFlow-AI Workflow Engine';
  const mimeType = config.mimeType || 'text/plain';

  // Retrieve user's OAuth token from SQLite persistence
  const tokenRecord = await getUserToken(userId, 'google');
  const accessToken = tokenRecord?.accessToken || config.accessToken;

  if (!accessToken) {
    throw new Error(`Google Drive OAuth token not found for user "${userId}". Please authorize Google Drive in settings.`);
  }

  const metadata = {
    name: fileName,
    mimeType,
  };

  const boundary = 'foo_bar_baz';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}\r\n\r\n` +
    fileContent +
    closeDelimiter;

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': `multipart/related; boundary=${boundary}`,
    },
    body: multipartRequestBody,
  });

  const responseData = await res.json();

  if (!res.ok) {
    throw new Error(`Google Drive API Error (${res.status}): ${responseData.error?.message || JSON.stringify(responseData)}`);
  }

  return {
    uploaded: true,
    fileId: responseData.id,
    fileName,
    mimeType,
  };
});
